### PR TITLE
Attempt to fix some issues with API calls using undefined

### LINKED ISSUE #1: Template creation/update not working in some cases
Some templates are failing to update, and others are failing to be created, but doing so silently so it looks like the change was successful.

I added logging output to determine what the actual response was:

plugin output:

```
Uploaded dist/template-name to sendwithus
```

actual API response:

```
response: Template not found
```

In other cases:

plugin output:

```
Uploaded dist/owner-booking-day-before-dropoff.html to sendwithus
```

api response:

```
response: Invalid email subject
```

and in other cases:

plugin output:

```
└── Updated version undefined in API
```

api response:

```
response: ValidationError: expected token 'end of print statement', got 'string' on line 185
```

### PR DESCRIPTION
**Pull request by brandonb927**
Fixes #1 hopefully!

### CODE REVIEW

File: tasks/sendwithus.coffee [hunk 1]
```diff
@@ -59,85 +62,54 @@ class Sendwithus
...
-    return requestp(requestOptions).then(
-      (response) ->
-        return response
-
+    return requestPromise.then(
+      (res) ->
+        return res
       (err) ->
-        grunt.log.error 'API request failed with statusCode:', err.statusCode
-        return err
```
Comment (brandonb927) [inline tasks/sendwithus.coffee:82]: This, as it turns out, was a big source of the problem. Because I was pushing the error back into the promise chain, I would have to catch it in every single promise termination in order to stem the errors. I moved this up into the API call and throw an error there so that it stops error propagation unless you manually invoke `catch` in the promise chain.

**Comment by chrispouliot** [comment]
👍
